server:
  port: 8085

spring:
  application:
    name: webflux-demo-1
  main:
    allow-bean-definition-overriding: true
  redis:
    node: ${REDIS_URL:dev-k8s.fosun.com:38543}
    password: ${REDIS_PASSWORD:sdcjn2xwdmicwSCJCN}