server:
  port: 8885

spring:
  application:
    name: webflux-demo-1
  main:
    allow-bean-definition-overriding: true
  redis:
    node: ${REDIS_URL__NO:dev-k8s.fosun.com:38543}
    password: ${REDIS_PASSWORD__NO:sdcjn2xwdmicwSCJCN}