server:
  port: 8702
spring:
  application:
    name: guard-server

eureka:
  client:
    service-url:
      # eureka 服务地址，如果是集群的话；需要指定其它集群eureka地址
#      defaultZone: http://localhost:8763/eureka/
      defaultZone: http://zecho.jasonzeng.top:8080/eureka
    enabled: true


