server:
  port: 8009
  address: 0.0.0.0

shenyu:
  client:
    registerType: http #zookeeper #etcd #nacos #consul
    serverLists: http://localhost:9095 #localhost:2181 #http://localhost:2379 #localhost:8848
    props:
      contextPath: /api
      appName: test-http
      port: 8009
      nacosNameSpace: local